/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as LangAuthRouteRouteImport } from './routes/$lang/auth/route'
import { Route as LangAccountRouteRouteImport } from './routes/$lang/account/route'
import { Route as LangAppRouteRouteImport } from './routes/$lang/_app/route'
import { Route as LangAppIndexRouteImport } from './routes/$lang/_app/index'
import { Route as ApiUsersIdRouteImport } from './routes/api/users.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LangAuthRegisterIndexRouteImport } from './routes/$lang/auth/register/index'
import { Route as LangAuthLoginIndexRouteImport } from './routes/$lang/auth/login/index'
import { Route as LangAccountProfilesIndexRouteImport } from './routes/$lang/account/profiles/index'
import { Route as LangAccountProfileSelectIndexRouteImport } from './routes/$lang/account/profile-select/index'
import { Route as LangAppShowsIndexRouteImport } from './routes/$lang/_app/shows/index'
import { Route as LangAppSearchIndexRouteImport } from './routes/$lang/_app/search/index'
import { Route as LangAppMyListIndexRouteImport } from './routes/$lang/_app/my-list/index'
import { Route as LangAppMoviesIndexRouteImport } from './routes/$lang/_app/movies/index'
import { Route as LangAccountProfilesIdIndexRouteImport } from './routes/$lang/account/profiles/$id/index'
import { Route as LangAccountProfilesIdRatingsIndexRouteImport } from './routes/$lang/account/profiles/$id/ratings/index'
import { Route as LangAccountProfilesIdEditIndexRouteImport } from './routes/$lang/account/profiles/$id/edit/index'

const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const LangAuthRouteRoute = LangAuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAccountRouteRoute = LangAccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAppRouteRoute = LangAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAppIndexRoute = LangAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangAppRouteRoute,
} as any)
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LangAuthRegisterIndexRoute = LangAuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => LangAuthRouteRoute,
} as any)
const LangAuthLoginIndexRoute = LangAuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => LangAuthRouteRoute,
} as any)
const LangAccountProfilesIndexRoute =
  LangAccountProfilesIndexRouteImport.update({
    id: '/profiles/',
    path: '/profiles/',
    getParentRoute: () => LangAccountRouteRoute,
  } as any)
const LangAccountProfileSelectIndexRoute =
  LangAccountProfileSelectIndexRouteImport.update({
    id: '/profile-select/',
    path: '/profile-select/',
    getParentRoute: () => LangAccountRouteRoute,
  } as any)
const LangAppShowsIndexRoute = LangAppShowsIndexRouteImport.update({
  id: '/shows/',
  path: '/shows/',
  getParentRoute: () => LangAppRouteRoute,
} as any)
const LangAppSearchIndexRoute = LangAppSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => LangAppRouteRoute,
} as any)
const LangAppMyListIndexRoute = LangAppMyListIndexRouteImport.update({
  id: '/my-list/',
  path: '/my-list/',
  getParentRoute: () => LangAppRouteRoute,
} as any)
const LangAppMoviesIndexRoute = LangAppMoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => LangAppRouteRoute,
} as any)
const LangAccountProfilesIdIndexRoute =
  LangAccountProfilesIdIndexRouteImport.update({
    id: '/profiles/$id/',
    path: '/profiles/$id/',
    getParentRoute: () => LangAccountRouteRoute,
  } as any)
const LangAccountProfilesIdRatingsIndexRoute =
  LangAccountProfilesIdRatingsIndexRouteImport.update({
    id: '/profiles/$id/ratings/',
    path: '/profiles/$id/ratings/',
    getParentRoute: () => LangAccountRouteRoute,
  } as any)
const LangAccountProfilesIdEditIndexRoute =
  LangAccountProfilesIdEditIndexRouteImport.update({
    id: '/profiles/$id/edit/',
    path: '/profiles/$id/edit/',
    getParentRoute: () => LangAccountRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/account': typeof LangAccountRouteRouteWithChildren
  '/$lang/auth': typeof LangAuthRouteRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/$lang/': typeof LangAppIndexRoute
  '/$lang/movies/': typeof LangAppMoviesIndexRoute
  '/$lang/my-list/': typeof LangAppMyListIndexRoute
  '/$lang/search/': typeof LangAppSearchIndexRoute
  '/$lang/shows/': typeof LangAppShowsIndexRoute
  '/$lang/account/profile-select/': typeof LangAccountProfileSelectIndexRoute
  '/$lang/account/profiles/': typeof LangAccountProfilesIndexRoute
  '/$lang/auth/login/': typeof LangAuthLoginIndexRoute
  '/$lang/auth/register/': typeof LangAuthRegisterIndexRoute
  '/$lang/account/profiles/$id/': typeof LangAccountProfilesIdIndexRoute
  '/$lang/account/profiles/$id/edit/': typeof LangAccountProfilesIdEditIndexRoute
  '/$lang/account/profiles/$id/ratings/': typeof LangAccountProfilesIdRatingsIndexRoute
}
export interface FileRoutesByTo {
  '/$lang': typeof LangAppIndexRoute
  '/$lang/account': typeof LangAccountRouteRouteWithChildren
  '/$lang/auth': typeof LangAuthRouteRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/$lang/movies': typeof LangAppMoviesIndexRoute
  '/$lang/my-list': typeof LangAppMyListIndexRoute
  '/$lang/search': typeof LangAppSearchIndexRoute
  '/$lang/shows': typeof LangAppShowsIndexRoute
  '/$lang/account/profile-select': typeof LangAccountProfileSelectIndexRoute
  '/$lang/account/profiles': typeof LangAccountProfilesIndexRoute
  '/$lang/auth/login': typeof LangAuthLoginIndexRoute
  '/$lang/auth/register': typeof LangAuthRegisterIndexRoute
  '/$lang/account/profiles/$id': typeof LangAccountProfilesIdIndexRoute
  '/$lang/account/profiles/$id/edit': typeof LangAccountProfilesIdEditIndexRoute
  '/$lang/account/profiles/$id/ratings': typeof LangAccountProfilesIdRatingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/_app': typeof LangAppRouteRouteWithChildren
  '/$lang/account': typeof LangAccountRouteRouteWithChildren
  '/$lang/auth': typeof LangAuthRouteRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/$lang/_app/': typeof LangAppIndexRoute
  '/$lang/_app/movies/': typeof LangAppMoviesIndexRoute
  '/$lang/_app/my-list/': typeof LangAppMyListIndexRoute
  '/$lang/_app/search/': typeof LangAppSearchIndexRoute
  '/$lang/_app/shows/': typeof LangAppShowsIndexRoute
  '/$lang/account/profile-select/': typeof LangAccountProfileSelectIndexRoute
  '/$lang/account/profiles/': typeof LangAccountProfilesIndexRoute
  '/$lang/auth/login/': typeof LangAuthLoginIndexRoute
  '/$lang/auth/register/': typeof LangAuthRegisterIndexRoute
  '/$lang/account/profiles/$id/': typeof LangAccountProfilesIdIndexRoute
  '/$lang/account/profiles/$id/edit/': typeof LangAccountProfilesIdEditIndexRoute
  '/$lang/account/profiles/$id/ratings/': typeof LangAccountProfilesIdRatingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$lang'
    | '/$lang/account'
    | '/$lang/auth'
    | '/api/users'
    | '/api/auth/$'
    | '/api/users/$id'
    | '/$lang/'
    | '/$lang/movies/'
    | '/$lang/my-list/'
    | '/$lang/search/'
    | '/$lang/shows/'
    | '/$lang/account/profile-select/'
    | '/$lang/account/profiles/'
    | '/$lang/auth/login/'
    | '/$lang/auth/register/'
    | '/$lang/account/profiles/$id/'
    | '/$lang/account/profiles/$id/edit/'
    | '/$lang/account/profiles/$id/ratings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$lang'
    | '/$lang/account'
    | '/$lang/auth'
    | '/api/users'
    | '/api/auth/$'
    | '/api/users/$id'
    | '/$lang/movies'
    | '/$lang/my-list'
    | '/$lang/search'
    | '/$lang/shows'
    | '/$lang/account/profile-select'
    | '/$lang/account/profiles'
    | '/$lang/auth/login'
    | '/$lang/auth/register'
    | '/$lang/account/profiles/$id'
    | '/$lang/account/profiles/$id/edit'
    | '/$lang/account/profiles/$id/ratings'
  id:
    | '__root__'
    | '/$lang'
    | '/$lang/_app'
    | '/$lang/account'
    | '/$lang/auth'
    | '/api/users'
    | '/api/auth/$'
    | '/api/users/$id'
    | '/$lang/_app/'
    | '/$lang/_app/movies/'
    | '/$lang/_app/my-list/'
    | '/$lang/_app/search/'
    | '/$lang/_app/shows/'
    | '/$lang/account/profile-select/'
    | '/$lang/account/profiles/'
    | '/$lang/auth/login/'
    | '/$lang/auth/register/'
    | '/$lang/account/profiles/$id/'
    | '/$lang/account/profiles/$id/edit/'
    | '/$lang/account/profiles/$id/ratings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LangRouteRoute: typeof LangRouteRouteWithChildren
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/auth': {
      id: '/$lang/auth'
      path: '/auth'
      fullPath: '/$lang/auth'
      preLoaderRoute: typeof LangAuthRouteRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/account': {
      id: '/$lang/account'
      path: '/account'
      fullPath: '/$lang/account'
      preLoaderRoute: typeof LangAccountRouteRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/_app': {
      id: '/$lang/_app'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangAppRouteRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/_app/': {
      id: '/$lang/_app/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangAppIndexRouteImport
      parentRoute: typeof LangAppRouteRoute
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/auth/register/': {
      id: '/$lang/auth/register/'
      path: '/register'
      fullPath: '/$lang/auth/register/'
      preLoaderRoute: typeof LangAuthRegisterIndexRouteImport
      parentRoute: typeof LangAuthRouteRoute
    }
    '/$lang/auth/login/': {
      id: '/$lang/auth/login/'
      path: '/login'
      fullPath: '/$lang/auth/login/'
      preLoaderRoute: typeof LangAuthLoginIndexRouteImport
      parentRoute: typeof LangAuthRouteRoute
    }
    '/$lang/account/profiles/': {
      id: '/$lang/account/profiles/'
      path: '/profiles'
      fullPath: '/$lang/account/profiles/'
      preLoaderRoute: typeof LangAccountProfilesIndexRouteImport
      parentRoute: typeof LangAccountRouteRoute
    }
    '/$lang/account/profile-select/': {
      id: '/$lang/account/profile-select/'
      path: '/profile-select'
      fullPath: '/$lang/account/profile-select/'
      preLoaderRoute: typeof LangAccountProfileSelectIndexRouteImport
      parentRoute: typeof LangAccountRouteRoute
    }
    '/$lang/_app/shows/': {
      id: '/$lang/_app/shows/'
      path: '/shows'
      fullPath: '/$lang/shows/'
      preLoaderRoute: typeof LangAppShowsIndexRouteImport
      parentRoute: typeof LangAppRouteRoute
    }
    '/$lang/_app/search/': {
      id: '/$lang/_app/search/'
      path: '/search'
      fullPath: '/$lang/search/'
      preLoaderRoute: typeof LangAppSearchIndexRouteImport
      parentRoute: typeof LangAppRouteRoute
    }
    '/$lang/_app/my-list/': {
      id: '/$lang/_app/my-list/'
      path: '/my-list'
      fullPath: '/$lang/my-list/'
      preLoaderRoute: typeof LangAppMyListIndexRouteImport
      parentRoute: typeof LangAppRouteRoute
    }
    '/$lang/_app/movies/': {
      id: '/$lang/_app/movies/'
      path: '/movies'
      fullPath: '/$lang/movies/'
      preLoaderRoute: typeof LangAppMoviesIndexRouteImport
      parentRoute: typeof LangAppRouteRoute
    }
    '/$lang/account/profiles/$id/': {
      id: '/$lang/account/profiles/$id/'
      path: '/profiles/$id'
      fullPath: '/$lang/account/profiles/$id/'
      preLoaderRoute: typeof LangAccountProfilesIdIndexRouteImport
      parentRoute: typeof LangAccountRouteRoute
    }
    '/$lang/account/profiles/$id/ratings/': {
      id: '/$lang/account/profiles/$id/ratings/'
      path: '/profiles/$id/ratings'
      fullPath: '/$lang/account/profiles/$id/ratings/'
      preLoaderRoute: typeof LangAccountProfilesIdRatingsIndexRouteImport
      parentRoute: typeof LangAccountRouteRoute
    }
    '/$lang/account/profiles/$id/edit/': {
      id: '/$lang/account/profiles/$id/edit/'
      path: '/profiles/$id/edit'
      fullPath: '/$lang/account/profiles/$id/edit/'
      preLoaderRoute: typeof LangAccountProfilesIdEditIndexRouteImport
      parentRoute: typeof LangAccountRouteRoute
    }
  }
}

interface LangAppRouteRouteChildren {
  LangAppIndexRoute: typeof LangAppIndexRoute
  LangAppMoviesIndexRoute: typeof LangAppMoviesIndexRoute
  LangAppMyListIndexRoute: typeof LangAppMyListIndexRoute
  LangAppSearchIndexRoute: typeof LangAppSearchIndexRoute
  LangAppShowsIndexRoute: typeof LangAppShowsIndexRoute
}

const LangAppRouteRouteChildren: LangAppRouteRouteChildren = {
  LangAppIndexRoute: LangAppIndexRoute,
  LangAppMoviesIndexRoute: LangAppMoviesIndexRoute,
  LangAppMyListIndexRoute: LangAppMyListIndexRoute,
  LangAppSearchIndexRoute: LangAppSearchIndexRoute,
  LangAppShowsIndexRoute: LangAppShowsIndexRoute,
}

const LangAppRouteRouteWithChildren = LangAppRouteRoute._addFileChildren(
  LangAppRouteRouteChildren,
)

interface LangAccountRouteRouteChildren {
  LangAccountProfileSelectIndexRoute: typeof LangAccountProfileSelectIndexRoute
  LangAccountProfilesIndexRoute: typeof LangAccountProfilesIndexRoute
  LangAccountProfilesIdIndexRoute: typeof LangAccountProfilesIdIndexRoute
  LangAccountProfilesIdEditIndexRoute: typeof LangAccountProfilesIdEditIndexRoute
  LangAccountProfilesIdRatingsIndexRoute: typeof LangAccountProfilesIdRatingsIndexRoute
}

const LangAccountRouteRouteChildren: LangAccountRouteRouteChildren = {
  LangAccountProfileSelectIndexRoute: LangAccountProfileSelectIndexRoute,
  LangAccountProfilesIndexRoute: LangAccountProfilesIndexRoute,
  LangAccountProfilesIdIndexRoute: LangAccountProfilesIdIndexRoute,
  LangAccountProfilesIdEditIndexRoute: LangAccountProfilesIdEditIndexRoute,
  LangAccountProfilesIdRatingsIndexRoute:
    LangAccountProfilesIdRatingsIndexRoute,
}

const LangAccountRouteRouteWithChildren =
  LangAccountRouteRoute._addFileChildren(LangAccountRouteRouteChildren)

interface LangAuthRouteRouteChildren {
  LangAuthLoginIndexRoute: typeof LangAuthLoginIndexRoute
  LangAuthRegisterIndexRoute: typeof LangAuthRegisterIndexRoute
}

const LangAuthRouteRouteChildren: LangAuthRouteRouteChildren = {
  LangAuthLoginIndexRoute: LangAuthLoginIndexRoute,
  LangAuthRegisterIndexRoute: LangAuthRegisterIndexRoute,
}

const LangAuthRouteRouteWithChildren = LangAuthRouteRoute._addFileChildren(
  LangAuthRouteRouteChildren,
)

interface LangRouteRouteChildren {
  LangAppRouteRoute: typeof LangAppRouteRouteWithChildren
  LangAccountRouteRoute: typeof LangAccountRouteRouteWithChildren
  LangAuthRouteRoute: typeof LangAuthRouteRouteWithChildren
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangAppRouteRoute: LangAppRouteRouteWithChildren,
  LangAccountRouteRoute: LangAccountRouteRouteWithChildren,
  LangAuthRouteRoute: LangAuthRouteRouteWithChildren,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

interface ApiUsersRouteChildren {
  ApiUsersIdRoute: typeof ApiUsersIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersIdRoute: ApiUsersIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LangRouteRoute: LangRouteRouteWithChildren,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
